git:
  submodule_override:
    "test/resource": "https://gitee.com/khs1994-php/resource"

pipeline:
  script:
    image: node:alpine
    commands:
    - export PATH=./node_modules/.bin:$PATH
    - npm install
    - npm test

  after_success:
    image: node:alpine
    # environment:
    #   - CODECOV_TOKEN=XXX
    commands:
    - npm run codecov
