git:
  submodule_override:
    "test/resource": "https://gitee.com/khs1994-php/resource"

pipeline:
  script:
    image: node:${NODE_VERSION}-alpine
    commands:
      - export PATH=./node_modules/.bin:$PATH
      - npm install --registry=https://registry.npm.taobao.org
      - npm test
    secrets: [node_tencent_ai_app_key,node_tencent_ai_app_id]
    volumes:
      - /tmp/node/caches:/root/.npm/_cacache
    privileged: true

  after_success:
    image: khs1994/node:git
    # environment:
    #   - CODECOV_TOKEN=XXX
    commands:
      - export PATH=./node_modules/.bin:$PATH
      - npm run codecov
    when:
      status: success
    secrets: [codecov_token]

  deploy:
    image: plugins/npm
    username: khs1994
    # password: mypassword
    # token: mytoken
    email: khs1994@khs1994.com
    registry: https://registry.npmjs.org
    when:
      event: tag
      status: success
    secrets: [npm_username,npm_password,npm_token]

matrix:
  NODE_VERSION:
    - "11"
    - "10"
