git:
  submodule_override:
    "test/resource": "https://gitee.com/khs1994-php/resource"

language: node_js

pipeline:
  install:
    image: khs1994/node:git
    commands:
      - npm install --registry=https://registry.npm.taobao.org

  script:
    image: node:${NODE_VERSION}-alpine
    # environment:
    #   - NODE_TENCENT_AI_APP_KEY=abc
    #   - NODE_TENCENT_AI_APP_ID=123
    commands:
      - export PATH=./node_modules/.bin:$PATH
      - npm test

  after_success:
    image: khs1994/node:git
    # environment:
    #   - CODECOV_TOKEN=XXX
    commands:
      - export PATH=./node_modules/.bin:$PATH
      - npm run codecov
      - rm -rf src/client/data.txt
    when:
      status: success

  deploy:
    # image: khs1994/deployer
    # environment:
    #   - NPM_TOKEN=""
    provider: npm
    email: khs1994@khs1994.com
    # api_key: $NPM_TOKEN
    # tag: next
    when:
      event: "tag"
      status: success
      matrix:
        NODE_VERSION: 11

matrix:
  NODE_VERSION:
    - 11
    - 10
