language: node_js

node_js:
- "11"
- "10"

cache: npm

install:
- npm install
#- npm install codecov --save-dev
#- npm install nyc --save-dev

script:
- npm run test

after_success:
- npm run codecov

# https://docs.travis-ci.com/user/deployment/npm/
deploy:
  provider: npm
  email: "khs1994@khs1994.com"
  api_key: $NPM_TOKEN
  on:
    tags: true
